name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # 🐍 Setup Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    #  Install dependencies
    - name: Install dependencies
      run: pip install -r requirements.txt

    #  SAST - Semgrep
    - name: Run Semgrep (SAST)
      continue-on-error: true
      run: |
        pip install semgrep
        semgrep --config=auto --error .

    #  Secrets Detection - Gitleaks
    - name: Run Gitleaks (Secrets Scan)
      continue-on-error: true
      run: |
        docker run --rm -v ${{ github.workspace }}:/repo \
        zricethezav/gitleaks detect --source /repo --exit-code 1

    #  Build Docker Image
    - name: Build Docker Image
      run: docker build -t devsecops-demo .

    #  Container Scan - Trivy
    - name: Scan Docker Image (Trivy)
      continue-on-error: true
      run: |
        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
        aquasec/trivy image --exit-code 1 --severity HIGH,CRITICAL devsecops-demo

    #  Run Application
    - name: Run Application Container
      run: |
        docker run -d -p 5000:5000 --name test-app devsecops-demo

    #  Wait for app
    - name: Wait for app to be ready
      run: sleep 15
    - name: Verify app is running
      run: |
        curl http://localhost:5000 || true

    #  DAST - OWASP ZAP
    - name: Run OWASP ZAP Scan
      continue-on-error: true
      run: |
        docker run --rm -t --network host \
          -v $(pwd):/zap/wrk \
          ghcr.io/zaproxy/zaproxy:stable
          -t http://localhost:5000 \
          -r zap-report.html || true

    - name: List files (debug)
      run: ls -la

    #  Upload ZAP Report
    - name: Upload ZAP Report
      uses: actions/upload-artifact@v4
      with:
        name: zap-report
        path: zap-report.html
   
    - name: List files (debug)
      run: ls -la
   
      #  Cleanup
    - name: Stop and remove container
      run: |
        docker stop test-app
        docker rm test-app

    #  Final message
    - name: Build Success Message
      run: echo "All security checks passed"